### ISSUE TITLE
Error 1 when running the Vocal Remover

### ISSUE THREAD

**Issue by ThePhantomOfTheOpera69** [Anjok07/ultimatevocalremovergui#129]
Traceback (most recent call last):
  File "C:\Users\Alex\Documents\Vocal Remover\VocalRemover.py", line 25, in <module>
    import inference_v2
  File "C:\Users\Alex\Documents\Vocal Remover\inference_v2.py", line 10, in <module>
    from lib_v2 import dataset
  File "C:\Users\Alex\Documents\Vocal Remover\lib_v2\dataset.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

[process exited with code 1]

I think it may have something to do with the Python installer failing to install to PATH, but I uninstalled and reinstalled several times and I still get this issue

**Comment by clippeh** [comment]
Hi,

I'm a total newbie but i had the same error and just installed the torch module via `pip install torch` in cmd. Don't really understand why the documentation says I had to download a 3gb pytorch (several times due to a cache problem) but maybe it's still used as well?...

The vocalremover.py also didn't open when double clicked but then I just navigated to my UVR-V4GUI folder via cmd `cd C:\Users\i7-3770User\Desktop\UVR-4GUI` and then opened the vocalremover.py via `python vocalremover.py`

It opened up ¯\_(ツ)_/¯

Hope it works

**Comment by ThePhantomOfTheOpera69** [comment]
sorry, but that doesn't fix it. I only have 1 python installation and I think the problem is to do with outdated installation instructions because i tried this out on multiple Virtual machines and still got the same issue ¯\_(ツ)_/¯

**Comment by Anjok07** [comment]
Please update to UVR 5.2.0 and use the installer.
