### ISSUE TITLE
[Linux] Please stop recommending people to break their systems

### ISSUE THREAD

**Issue by mitsuami-megane** [Anjok07/ultimatevocalremovergui#1578]
I find that this specific recommendation in the installation guide is recklessly dangerous.

```bash
sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED
```

This can possibly cause people's system packages to break and system upgrades fail. I recommend using pipx instead, or at least providing a manual installation guide using venv.

**Comment by s-b-repo** [comment]
true

**Comment by mpicard** [comment]
This project looks abandoned

**Comment by Anjok07** [comment]
@mitsuami-megane Thank you for bringing this to my attention! Those instruction were written sometime ago. I went head and updated them accordingly to use venv - https://github.com/Anjok07/ultimatevocalremovergui/blob/master/README.md#linux-installation-updated-instructions

**Comment by Anjok07** [comment]
A quick note on the previous Linux installation instructions I shared a while back. Those instructions were written over two years ago based on guidance I thought was reliable at the time. Unfortunately, some of that advice turned out to be less than ideal, and certain steps, like modifying system files, could cause issues for users.

I really appreciate the trust you all placed in this project, and I apologize if these instructions caused any trouble. To improve things, I’ve completely overhauled the installation guide to reflect current best practices. The updated instructions include proper steps for setting up a virtual environment, ensuring the program’s dependencies stay isolated and don’t interfere with your system.

The revised instructions are now live in the Linux Installation section, so please check them out for any future installs or updates.

Thank you all for your patience and continued support. Your feedback has been incredibly helpful in making this project better for everyone.

 https://github.com/Anjok07/ultimatevocalremovergui/blob/master/README.md#linux-installation-updated-instructions

**Comment by montvid** [comment]
@Anjok07 thanks for the new install instructions but unfortunately they don't work with python 3.12. In python 3.11. imp is deprecated and is turned into importlib in 3.12. The temporary solution is known, I guess the maintainer could fix this.

> replace `import imp` with `import importlib as imp`

**Comment by omnipotentbird** [comment]
> @Anjok07 thanks for the new install instructions but unfortunately they don't work with python 3.12. In python 3.11. imp is deprecated and is turned into importlib in 3.12. The temporary solution is known, I guess the maintainer could fix this.
> 
> > replace `import imp` with `import importlib as imp`
> 
> Oh, i see it is an error in a external dependency:
> 
> ```
> pipx >(analyze_pip_output:311): pip seemed to fail to build package:
>     audioread==3.0.0
> 
> Some possibly relevant errors from pip install:
>     error: subprocess-exited-with-error
>     ModuleNotFoundError: No module named 'imp'
> ```

How do you resolve this?

**Comment by RustoMCSpit** [comment]
@omnipotentbird fixed that here https://github.com/Anjok07/ultimatevocalremovergui/issues/1674
