### ISSUE TITLE
FileNotFoundError - "[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Steeev64** [Anjok07/ultimatevocalremovergui#186]
When the file starts to be saved during processing, it gives an error FileNotFoundError - "[Errno 2] No such file or directory. In mdx models 
![image](https://user-images.githubusercontent.com/106892102/172029674-937ee07d-cae6-4094-a074-27ecfdb7e29b.png)

**Comment by Anjok07** [comment]
@Steeev64 - This error is occurring due to the current set Noise Reduction. You can't set Noise Reduction over 10. Please set it to 10 or under to process your files or download the latest patch that addresses this bug. 

Patch information can be found here - https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v5.2.0
