### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by snoopytl** [Anjok07/ultimatevocalremovergui#230]
in ensemble options interface，everything can't be displayed completely
![image](https://user-images.githubusercontent.com/29892766/180673406-a01aaee7-48d2-495c-8fb5-fb60427e89df.png)

**Comment by RisingInIris2017** [comment]
the same issue, UVR version 5.4.
My OS is Windows 10 Home 21H2.
I set the system scaling to 124%, maybe this is the cause of the issue.

**Comment by RisingInIris2017** [comment]
I have found the solution to this issue:
This issue is caused by Windows system custom scaling, my 124% scaling for example.
You will solve this issue simply by the following two steps:
1. Disable your system's custom scaling. For example, disable `124%` and replace it with one of the Windows default scalings.
    Due to my resolution is 1080p, `100%` will make icons and texts too small and difficult to read, I chose `125%` instead.
2. After this, you will see the display issue is gone, but the window of UVR becomes blur. To solve this, right click on the `UVR.exe` and go to the `Properties` menu. Open its `High DPI settings`, and enable all the options in this menu.
3. Then you can enjoy a clear and full displayed UVR.
Hope this is helpful to you!

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
