### ISSUE TITLE
Er hu issues!

### ISSUE THREAD

**Issue by yaohui185** [Anjok07/ultimatevocalremovergui#290]
It can not tell the difference between Vocals and the Er hu, Er hu is a kind of chinese traditional instrument.

**Comment by otomad** [comment]
I feel that it seems to be unsolvable. Because the tone of erhu (or other Chinese instruments such as flute and xiao) is very similar to human voice.

However, the most important thing is that the erhu sound appears and disappears after a while, so it may feel better to simply remove it completely without leaving any traces.

**Comment by yaohui185** [comment]
Thanks for your reply and advice,anyway,it's a great Vocal remover!










At 2022-11-11 13:07:30, "Ranne" ***@***.***> wrote:

I feel that it seems to be unsolvable. Because the tone of erhu (or other Chinese instruments such as flute and xiao) is very similar to human voice.

However, the most important thing is that the erhu sound appears and disappears after a while, so it may feel better to simply remove it completely without leaving any traces.
