### ISSUE TITLE
Size mismatch problem

### ISSUE THREAD

**Issue by Diego92Ita** [Anjok07/ultimatevocalremovergui#81]
**Describe the bug**
I'm trying to use UV5. Whenever I type the command to isolate the vocals, i get a long error saying something about "Size mismatch".

**To Reproduce**
1. Open Terminal
2. Type "python inference.py -g 0 -m modelparams/4band_44100.json -P models/NewLayer_4band_3.pth -i "PATH" (obviously in PATH I typed the correct file path to choose)
**Expected behavior**
The program should start and isolate the vocals from the song

**Screenshots**
<img width="2560" alt="Schermata 2021-06-23 alle 17 18 49" src="https://user-images.githubusercontent.com/63115610/123123570-37de1580-d447-11eb-9991-039ab4677821.png">
<img width="2560" alt="Schermata 2021-06-23 alle 17 19 13" src="https://user-images.githubusercontent.com/63115610/123123641-46c4c800-d447-11eb-8043-baf45aacda7e.png">

**Desktop:**
 - OS

**Comment by aufr33** [comment]
NewLayer_4band_3.pth - This model uses a different architecture. Frequency cut-off is 20000 Hz. Must be used with 4band_44100.json file! Please include '-n 129605KB' within the inference command to run this model!

**Comment by geraldoramos** [comment]
Hi,

Reopening this since I'm having the same issue and the suggested approach did not work.

I've tried to use any of the [July](https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/5.0.2) models as following:

```
file_path='bin/example/test.wav'
model_path='models/HP2-4BAND-3090_4band_2.pth'
param_path='modelparams/4band_44100.json'

python3 inference.py -n 129605KB -g 0 -m $param_path -P $model_path -i $file_path
```

I tried with and without the `-n 129605KB` flag. Also tried all the other models in the new 5.0.2 release. I'm using the recommended JSON as well.

The error returned is the following (many lines of these):
``` 
size mismatch for aux1_out.weight: copying a param with shape torch.Size([2, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 16, 1, 1]).
        size mismatch for aux2_out.weight: copying a param with shape torch.Size([2, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 16, 1, 1]).
```

Other models work fine, such as `MGM-v5-4Band-44100-BETA1`.

Any help is appreciated!

Thanks!
